# Generated by Django 5.2.15 on 2026-06-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('monthly_request_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_token_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
