# Generated by Django 5.2.15 on 2026-06-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_budget_usd',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], default='user', max_length=20),
        ),
    ]
